### ISSUE TITLE
仓库拉下来之后无法运行，控制台提示如下

### ISSUE THREAD

**Issue by NO-MAP** [MuRongXiaoDouBi/koa-typescript-cms#1]
仓库拉下来之后无法运行，控制台提示如下

`
Server running on port 3001
(node:3368) [SEQUELIZE0002] DeprecationWarning: The logging-option should be either a function or false. Default: console.log
Executing (default): CREATE TABLE IF NOT EXISTS `Users` (`id` INTEGER auto_increment  COMMENT 'ID', `nickname` VARCHAR(128) COMMENT '用户昵称', `email` VARCHAR(128) UNIQUE COMMENT '用户邮箱', `password` VARCHAR(64) COMMENT '用
户密码', `openid` VARCHAR(128) UNIQUE COMMENT '微信小程序openid', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, `deleted_at` DATETIME, PRIMARY KEY (`id`)) ENGINE=InnoDB;
Executing (default): SHOW INDEX FROM `Users`
`

访问接口  返回的是NOT FOUND

**Comment by murongg** [comment]
请问程序有没有全部运行起来，如果运行起来应该会打印路由信息。

**Comment by NO-MAP** [comment]
有全部运行起来，路由信息完全打印了，然后控制台就提示了如上的信息。

**Comment by murongg** [comment]
好的，晚上下班后我看一下，给您回复

**Comment by NO-MAP** [comment]
按照控制台提示，把数据库配置的logging改为false或者是一个方法后，就没有这个警告了; 但是访问
`http://localhost:3001/`
的任何接口返回的都是404，貌似是通过文件加载路由的方式并没有生效，你那边能复现出这个问题么？

**Comment by NO-MAP** [comment]
好吧，我已经解决了，你的这个仓库代码貌似是有缺失吧。
init.ts 里面路由加载完成后需要交由app进行一次use操作，少了这一步关键代码.....
`
app.use(mainRouter.routes());
`

**Comment by murongg** [comment]
抱歉哈，朋友，最近面临毕业事情比较多，处理东西的速度比较迟钝，如果你方便的话，可以提交个PR吗
